---
- hosts: localhost
  vars:
    clean_up_tests: "1"
  tasks:
    - name: Compile LeoDB and Tests
      command:
        cmd: >
          ansible-playbook run.yml -e build_tests=1 -e clean_up=0
    - name: TEST KEY
      command:
        cmd: >
          ./test_key
    - name: TEST OPERATORS
      command:
        cmd: >
          ./test_operators
    - name: TEST VALUE
      command:
        cmd: >
          ./test_value
    - name: Clean up
      block:
        - name: Clean up directory
          when: "{{ clean_up_tests }} == 1 "
          file:
            path: '{{ item }}'
            state: absent
          with_items:
            - test_value
            - test_key
            - test_operators
            - Makefile
            - leodb.cbp
            - leodb
            - CMakeCache.txt
            - cmake_install.cmake
            - tests/CMakeFiles
            - tests/cmake_install.cmake
            - tests/libleodb-tests.a
            - tests/Makefile
            - lib
            - tests/CMakeFiles
            - external/googletest-build
            - external/googletest-download
            - external/clipp.h
            - external/CMakeList.txt.in
            - CMakeFiles
            - cmake-build-normal
            - src/CMakeFiles
            - cmake_install.cmake
            - src/libleodb-src.a
            - src/Makefile
            - src/libleodb-src.a
            - src/cmake_install.cmake
            - src/CmakeFiles