---
- hosts: localhost
  vars:
    build_tests: "0"
    clean_up: "1"
  tasks:
    - name: Starting to compile
      block:
        - name: Compile CMakeList File
          command:
            cmd: >
              cmake . -DBUILD_TESTS={{ build_tests }}
        - name: Make File
          command:
            cmd: >
              make
        - name: Run LeoDB
          command:
            cmd: >
              ./leodb
          register: output
        - debug: msg="{{ output.stdout }}"
    - name: Clean up
      block:
        - name: Clean up directory
          when: "{{ clean_up }} == 1"
          file:
            path: '{{ item }}'
            state: absent
          with_items:
            - test_value
            - test_key
            - test_operators
            - Makefile
            - leodb.cbp
            - leodb
            - CMakeCache.txt
            - cmake_install.cmake
            - tests/CMakeFiles
            - tests/cmake_install.cmake
            - tests/libleodb-tests.a
            - tests/Makefile
            - lib
            - tests/CMakeFiles
            - external/googletest-build
            - external/googletest-download
            - external/clipp.h
            - external/CMakeList.txt.in
            - CMakeFiles
            - cmake-build-normal
            - src/CMakeFiles
            - cmake_install.cmake
            - src/libleodb-src.a
            - src/Makefile
            - src/libleodb-src.a
            - src/cmake_install.cmake
            - src/CmakeFiles