---
- hosts: localhost
  tasks:
    - name: Compile Test Code
      block:
        - name: Check if we've already compiled
          stat:
            path: "{{ path_to_leoDB }}/bin/leodb"
          register: compiled_check
        - name: Running `cmake . -DBUILD_TESTS=1`
          shell:
            cmd: cd "{{ path_to_leoDB }}" && cmake . -DBUILD_TESTS=1
          when: compiled_check.stat.exists == false
        - name: Running `make`
          shell:
            cmd: cd "{{ path_to_leoDB }}" && make
          when: compiled_check.stat.exists == false
    - name: Setting test flags
      set_fact:
        run_test: "{{ lookup('env','RUN_TEST') }}"
    - name: "Running {{ item }} Tests..."
      include_tasks: BenchmarkTests/runTest.yml
      vars:
        clean_up: 1
      loop:
        - "{{ run_test }}"